import { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar1 from '../components/navbar'
import useSWR from "swr";
import { apiLink, apiUrl } from "../config/config";
// import { fetcher } from "../helper/network";

const Home: NextPage = () => {

  const { data, error } = useSWR(
    apiLink + '/room',
    fetcher
  );

  const mapItem = (item: any) => {
    console.log(item);
    return <HotelItem item={item}/> 
  }


  const HotelItem: React.FC<{ item: any }> = ({ item }) => {
    return (
      
      <div className="card shadow" style={{width: '18rem'}}>
      <img src="img/bg3.jpg" className="card-img-top" alt="img/bg2.jpg" />
      <div className="card-body text-center">
        <h5 className="card-title">{{item.tipe}}</h5>
        <p className="card-text">Rp {{item.harga}}</p>
      </div>
      </div>
      
    )
  }

export default function Home() {
  return (

    <div className=''>
      {/* header */}
      <Head>
        <title>Hotel Boo - Boo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css"></link>
      </Head>

      {/* navbar */}
      <Navbar1/>

      {/* banner */}
      <div className="banner"></div>

      {/* rooms */}
      <section className='rooms'>
      <div className="container pt-4 mb-4">
          <h1 className="text-center text-dark">Rooms</h1>
        <div className="d-flex justify-content-center pt-4 gap-5">

        {data && data.map(mapItem)}

              {/* <div className="card shadow" style={{width: '18rem'}}>
                <img src="img/bg3.jpg" className="card-img-top" alt="img/bg2.jpg" />
                <div className="card-body text-center">
                  <h5 className="card-title">Single Bed</h5>
                  <p className="card-text">Rp 250.000</p>
                </div>
              </div>

              <div className="card shadow" style={{width: '18rem'}}>
                <img src="img/bg3.jpg" className="card-img-top" alt="img/bg2.jpg" />
                <div className="card-body text-center">
                  <h5 className="card-title">Twin Bed</h5>
                  <p className="card-text">Rp 450.000</p>
                </div>
              </div> */}
              
        </div>
      </div>
      </section>

      {/* contact */}
      <section className="contact pt-4 mb-4">
        <div className="container">
        <div className="row d-flex justify-content-center">

          <div className="col">
            <h1 className='text-center mb-4 text-dark'>Contact Us</h1>
            <p className='px-5 text-dark'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa soluta voluptas sed accusamus odio dignissimos quibusdam maiores fugit cupiditate perspiciatis laborum tempora, tempore ab dolores repellat molestias consequuntur natus repudiandae.</p>
            <div className="wa px-5 mb-2">
              <a href=""><i className="bi bi-whatsapp"></i> 0801283821</a>
            </div>
            
            <div className="mail px-5">
              <a href=""><i className="bi bi-envelope"></i> ara@mine.com</a>
            </div>
          </div>
          
          <div className="col">
            <div className="card p-3 shadow" style={{width: '30rem'}}>
              <form action="" method="post">
                  <div className="mb-3 text-center">
                    <label className='from-label' htmlFor="">Nama</label>
                    <input type="text" name='nama' className='form-control'/>
                  </div>

                  <div className="mb-3 text-center">
                    <label className='from-label' htmlFor="">Email</label>
                    <input type="text" name='nama' className='form-control'/>
                  </div>

                  <div className="mb-4 text-center">
                    <label className='from-label' htmlFor="">No telp</label>
                    <input type="text" name='nama' className='form-control'/>
                  </div>

                  <div className="mb-3">
                    <button className='btn btn-primary' style={{width: '100%'}}>Enter</button>
                  </div>
              </form>
            </div>
          </div>
          </div>
        </div>
      </section>

      <section>
          <footer className="text-center text-lg-start">
          <div className="text-center text-white p-3">
              <b>&#9400; 2022</b>
          </div>
        </footer>
      </section>

    </div>
  )
}
