import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { NextPage } from 'next'
import Image from 'next/image'
import Navbar2 from '../components/navbar2'

export default function Home() {
return (

    <div className=''>
      {/* header */}
    <Head>
        <title>Hotel Boo - Boo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css"></link>
    </Head>

    <div className="loginBanner"></div>

    <Navbar2/>

    <div className="loginF d-flex justify-content-center">
        <div className="card p-3" style={{width: '28rem'}}>
            <form action='' method='POST'>
                <div className="mb-3">
                    <label htmlFor="exampleInputEmail1" className="form-label">Username</label>
                    <input type="email" className="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" />
                    <div id="emailHelp" className="form-text"></div>
                </div>
                <div className="mb-3">
                    <label htmlFor="exampleInputPassword1" className="form-label">Password</label>
                    <input type="password" className="form-control" id="exampleInputPassword1" />
                </div>
                <div className="mb-3 form-check">
                    <input type="checkbox" className="form-check-input" id="exampleCheck1" />
                    <label className="form-check-label" htmlFor="exampleCheck1">Check me out</label>
                </div>
                <button type="submit" className="btn btn-primary" style={{width: '100%'}}>Submit</button>
            </form>
        </div>
    </div>
    
    <section>
          <footer className="text-center text-lg-start">
          <div className="text-center text-white p-3">
              <b>&#9400; 2022</b>
          </div>
        </footer>
      </section>
    </div>

    )
}
